### ISSUE TITLE
Is django-attachments compatible with django 1.8?

### ISSUE THREAD

**Issue by erichschroeter** [bartTC/django-attachments#27]
Do I have to add an `attachments` field to my models that I wish to attach attachments to?

    VariableDoesNotExist at /testproject/requirements/1/
    Failed lookup for key [attachments] in u"[{'False': False, 'None': None, 'True': True}, {}, {}, {'project': <Project: testproject>, 'requirement': <Requirement: 1: A test requirement.>, u'object': <Requirement: 1: A test requirement.>, u'view': <requirements.views.RequirementRead object at 0x7f4fa42bf890>}]"
    Request Method: GET
    Request URL:    http://localhost:8000/testproject/requirements/1/
    Django Version: 1.8.5
    Exception Type: VariableDoesNotExist
    Exception Value:    
    Failed lookup for key [attachments] in u"[{'False': False, 'None': None, 'True': True}, {}, {}, {'project': <Project: testproject>, 'requirement': <Requirement: 1: A test requirement.>, u'object': <Requirement: 1: A test requirement.>, u'view': <requirements.views.RequirementRead object at 0x7f4fa42bf890>}]"
    Exception Location: /home/erich/.virtualenvs/reqtangle/local/lib/python2.7/site-packages/django/template/base.py in _resolve_lookup, line 839
    Python Executable:  /home/erich/.virtualenvs/reqtangle/bin/python
    Python Version: 2.7.6
    Python Path:    
    ['/home/erich/src/reqtangle/reqtangle',
     '/home/erich/.virtualenvs/reqtangle/lib/python2.7',
     '/home/erich/.virtualenvs/reqtangle/lib/python2.7/plat-x86_64-linux-gnu',
     '/home/erich/.virtualenvs/reqtangle/lib/python2.7/lib-tk',
     '/home/erich/.virtualenvs/reqtangle/lib/python2.7/lib-old',
     '/home/erich/.virtualenvs/reqtangle/lib/python2.7/lib-dynload',
     '/usr/lib/python2.7',
     '/usr/lib/python2.7/plat-x86_64-linux-gnu',
     '/usr/lib/python2.7/lib-tk',
     '/home/erich/.virtualenvs/reqtangle/local/lib/python2.7/site-packages',
     '/home/erich/.virtualenvs/reqtangle/lib/python2.7/site-packages']
    Server time:    Thu, 22 Oct 2015 15:18:33 +0000

**Comment by bartTC** [comment]
The develop branch is compatible with 1.8+ and is merged/released shortly.
