### ISSUE TITLE
Unable to open attachments with the link provide by your system

### ISSUE THREAD

**Issue by darkicex3** [bartTC/django-attachments#29]
I can't open any attachment files with the link : http://127.0.0.1:8000/attachments/article_article/15/my_file.pdf

<img width="733" alt="screen shot 2016-05-31 at 09 32 13" src="https://cloud.githubusercontent.com/assets/9675021/15660709/98eeb39e-2712-11e6-8d18-521e33f2dd4d.png">

I know that I have to create my own view and and an url, but your Django app don't do that already ? Maybe my configuration is bad.

**Comment by bartTC** [comment]
I think your `MEDIA_URL|PATH` setting is not setup properly and/or you're not serving static files. Please check and reopen if you think its an application issue.

**Comment by darkicex3** [comment]
Yes exactly thank you
