### ISSUE TITLE
Only allow certain types to be attached

### ISSUE THREAD

**Issue by panosl** [bartTC/django-attachments#3]
A patch that allows users to specify the type of files that can be attached:

ATTACHMENTS_ALLOWED_TYPES = '.jpg .png .jpeg .gif .bmp'

'' is special and everything can be attached.

http://panos.solhost.org/temp/allowed_types.patch

**Comment by dmarcelino** [comment]
@bartTC I have a similar albeit different requirement. Is there currently a way to restrict which file types can be attached (globally or per model/form)? If not can you point me to a way to work around it?
