### ISSUE TITLE
Current User in the path of the attachment file

### ISSUE THREAD

**Issue by foxmask** [bartTC/django-attachments#34]
Hi,
Will it be possible to have the current user added here  https://github.com/bartTC/django-attachments/blob/master/attachments/models.py#L14-L18 ? 
Thus that will facilitate the identification of the owner to restore files, in case of filesystem problem (and without running any SQL query)
Regards

**Comment by bartTC** [comment]
Possible, but very specific and not something you can turn on/off with a setting. I suggest you to fork the project and modify it to your needs.

**Comment by foxmask** [comment]
Thanks for your suggestion
