### ISSUE TITLE
Unit test error: jango.template.exceptions.TemplateSyntaxError: 'attachment_form' did not receive value(s) for the argument(s): 'name', 'id', 'next_url'

### ISSUE THREAD

**Issue by Alireza2n** [bartTC/django-attachments#36]
Hi,
When running the command "python3 runtests.py" for attachments app, 6 unit tests fail with following error:
`django.template.exceptions.TemplateSyntaxError: 'attachment_form' did not receive value(s) for the argument(s): 'name', 'id', 'next_url'`

**Comment by bartTC** [comment]
🤔  This is working fine for me. 

```
(attachments)  ~/Workspace/django-attachments master$ python3 runtests.py
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.................
----------------------------------------------------------------------
Ran 17 tests in 2.098s

OK
Destroying test database for alias 'default'...
```

What Python3 version is that? And could you run tox? 

```
$ pip install tox
$ tox -c tox.ini
```

**Comment by bartTC** [comment]
I was able to reproduce that. You probably didn't install the attachments app itself. I updated the testing docs in e115774f69544001022cda5980a524a5198d76f4, that should fix it for you. Please reopen if not.
