### ISSUE TITLE
overriding __str__ does not work on python 3.6

### ISSUE THREAD

**Issue by jangeador** [bartTC/django-attachments#45]
The __str__ method on the `Attachment` model is not getting interpolated is returning a literal `{username} attached {filename}`

This model method:
```py3
    def __str__(self):
        return _('{username} attached {filename}') % {
            'username': self.creator.get_username(),
            'filename': self.attachment_file.name
        }
```

**Comment by bartTC** [comment]
should be good, please try it again.

**Comment by jangeador** [comment]
Oh, I was working on it as well. You might want to add the test from my PR #48 it tests that __str__ method.

**Comment by jangeador** [comment]
Thanks for getting on that so quickly by the way. You're awesome!
