### ISSUE TITLE
Attach additional custom metadata

### ISSUE THREAD

**Issue by alex-kowalczyk** [bartTC/django-attachments#50]
Is there a simple way to attach some custom metadata to the files being uploaded without forking the code  overriding the views, models etc?  Would be great e.g. to define attachment kind (not content type, rather a kind of business kind)

**Comment by bartTC** [comment]
There's a https://github.com/bartTC/django-attachments/blob/master/attachments/apps.py which you could override and replace the Attachment model with one that fits our need.
