### ISSUE TITLE
Redirected to project root ('/') upon attachment submit

### ISSUE THREAD

**Issue by mattburlage** [bartTC/django-attachments#54]
attachments\views.py has, on line 55:

`next_ = request.POST.get('next_', '/')`

which should be

`next_ = request.POST.get('next', '/')`

**Comment by mattburlage** [comment]
pull req https://github.com/bartTC/django-attachments/pull/55#issue-253076717

**Comment by bartTC** [comment]
Uh, thanks!  Refs bb9bf0efe71fd2b1cfc0d2c102ad414b69784cb3

**Comment by bartTC** [comment]
I made a v1.4 release with this fix.
