### ISSUE TITLE
No module named 'django.contrib.staticfilesattachments'

### ISSUE THREAD

**Issue by flowl** [bartTC/django-attachments#58]
I couldn't get it to work using Python 3.6 and Django 2.2
The migrate doesn't do anything and some imports are missing/not available.

**Comment by bartTC** [comment]
You're clearly missing a comma in your INSTALLED_APPS settings. This is not a problem of this application.

**Comment by flowl** [comment]
You are right, sorry. 
I did expect python to complain and not just merge the strings lol but nvm.
