### ISSUE TITLE
v1.7 db_index for object_id field fails on MariaDB

### ISSUE THREAD

**Issue by atodorov** [bartTC/django-attachments#79]
The reason is that it is a TextField with unknown/unlimited length instead of a CharField with a fixed length. MariaDB (probably MySQL as well) doesn't like this and fails when applying the 0004 migration. 

@bashu, @bartTC from the original issue #61 I think a CharField(max_length=64) will work just as fine. Any objections for changing it  ?

**Comment by bashu** [comment]
> Any objections for changing it ?

@atodorov nope!
