### ISSUE TITLE
Pipfile vs tox.ini

### ISSUE THREAD

**Issue by atodorov** [bartTC/django-attachments#98]
@bartTC what is `Pipfile` and what is it used for? 

My original reason for asking is that I see `Pipfile.lock` which has lots of outdated dependencies but these are not dependencies we ship via `setup.py/setup.cfg` so not sure what they represent. Looks like something old. 

Then I've noticed that Pipfile uses pytest to execute the test suite however `.travis-ci.yml` which I'm trying to convert into GitHub actions uses `tox` instead. It looks like there are 2 different ways to execute tests. 

Given that Pipfile is older and hasn't seen any updates recently I'm thinking we could remove it in favor of GitHub Actions + tox ?

**Comment by bartTC** [comment]
Pipfile is the config file of `pipenv`. https://pipenv.pypa.io/en/latest/ I used it for local development. But I switched to pdm recently which I like a lot more.


It's not related to tox and testing, those do just install the package using it's setup.py  You can run tox with github actions pretty easily:

https://github.com/bartTC/django-markup/blob/main/tox.ini#L9-L15
https://github.com/bartTC/django-markup/blob/main/.github/workflows/push.yml#L22
